version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka3:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-eagle:
    image: nickzurich/kafka-eagle
    restart: always
    ports:
      - "8048:8048"
    environment:
      KE_ZK_CONNECT: zookeeper:2181
      KE_ZK_SESSION_TIMEOUT: 4000
      KE_ZK_CONNECTION_TIMEOUT: 6000
      KE_OFFSET_STORAGE: kafka
      KE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KE_ADVERTISED_HOST_NAME: localhost
    depends_on:
      - zookeeper
      - kafka1
        kafka2
        kafka3
      # 假设kafka2和kafka3也在这里列出