version: '3'
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-lable
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/my.cnf
      # 数据库I还原目录 可将需要还原的sql文件放在这里
      #- /apps/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=test"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
